[package]
name = "envfmt"
version = "0.1.0"
authors = ["pyk <gm@pyk.sh>"]
edition = "2024"
description = "Expands environment variables in string"
documentation = "https://pyk.sh/envfmt"
homepage = "https://pyk.sh/envfmt"
repository = "https://github.com/pyk/envfmt"
license = "MIT"


